-- -----------------------------------------------------
-- Table PROVEEDOR
-- -----------------------------------------------------
DROP TABLE IF EXISTS PROVEEDOR ;

CREATE TABLE IF NOT EXISTS PROVEEDOR (
	idPROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(45) NOT NULL);

-- -----------------------------------------------------
-- Table PRODUCTOS
-- -----------------------------------------------------
DROP TABLE IF EXISTS PRODUCTOS ;

CREATE TABLE IF NOT EXISTS PRODUCTOS (
	idPRODUCTOS INT AUTO_INCREMENT PRIMARY KEY,
	idPROVEEDOR INT,
	CATEGORIA VARCHAR(45),
	ARTICULO VARCHAR(45) NOT NULL,
	CODIGO VARCHAR(45) NOT NULL,
	DESCRIPCION VARCHAR(45) NOT NULL,
	MARCA VARCHAR(45) NOT NULL,
	LINEA VARCHAR(45) NOT NULL,
	CLAVE VARCHAR(45) NOT NULL,
	OBSERVACIONES VARCHAR(45) NOT NULL,
	FECHA VARCHAR(45) NOT NULL,
	FOTO VARCHAR(45) NOT NULL,
	LINEAS VARCHAR(45) NOT NULL,
	GRUPOS VARCHAR(45) NOT NULL,
	EXIST BOOLEAN NOT NULL DEFAULT 0,
	CANTIDAD INT(10) NOT NULL,
	PRECIO FLOAT NOT NULL,
	PRECIO_LISTA FLOAT NOT NULL,
	ORDEN_ESPECIAL FLOAT NOT NULL,
	PRECIO_ANTERIOR FLOAT NOT NULL,
	PRECIO_NUEVO FLOAT NOT NULL,
	INCREMENTO FLOAT NOT NULL,
	UXCTN FLOAT NOT NULL,
	PRECIO_L4 FLOAT NOT NULL,
	EQUIVALENCIA FLOAT NOT NULL,
	CANTIDAD_POR_CARTON INT(10) NOT NULL,
		FOREIGN KEY (idPROVEEDOR) REFERENCES PROVEEDOR (idPROVEEDOR),
		FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (CATEGORIA));
-- -----------------------------------------------------
-- Table ORDEN
-- -----------------------------------------------------
DROP TABLE IF EXISTS ORDEN ;

CREATE TABLE IF NOT EXISTS ORDEN (
	idORDEN INT AUTO_INCREMENT PRIMARY KEY,
	idPRODUCTOS INT,
	ARTICULO VARCHAR(45) NOT NULL,
	DESCRIPCION VARCHAR(45) NOT NULL,
	PRECIO FLOAT NOT NULL,
		FOREIGN KEY (idPRODUCTOS) REFERENCES PRODUCTOS (idPRODUCTOS));
-- -----------------------------------------------------
-- Table CATEGORIA
-- -----------------------------------------------------
DROP TABLE IF EXISTS CATEGORIA ;

CREATE TABLE IF NOT EXISTS CATEGORIA (
	idCATEGORIA INT AUTO_INCREMENT NOT NULL,
	CATEGORIA VARCHAR(45) NOT NULL,
	DESCRIP_CATEGORIA VARCHAR(45) NOT NULL,
	CLASE VARCHAR(45) NOT NULL,
	GENERO VARCHAR(45) NOT NULL,
	NO_PARTE VARCHAR(45) NOT NULL,
	ORIGEN VARCHAR(45) NOT NULL,
	UNIDAD VARCHAR(45) NOT NULL,
	PRIMARY KEY (idCATEGORIA, CATEGORIA));