-- -----------------------------------------------------
-- Table PROVEEDOR
-- -----------------------------------------------------
DROP TABLE IF EXISTS PROVEEDOR ;

CREATE TABLE IF NOT EXISTS PROVEEDOR (
	idPROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(45) NOT NULL);

-- -----------------------------------------------------
-- Table PRODUCTOS
-- -----------------------------------------------------
DROP TABLE IF EXISTS PRODUCTOS ;

CREATE TABLE IF NOT EXISTS PRODUCTOS (
	idPRODUCTOS INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	idPROVEEDOR INT,
	CATEGORIA VARCHAR(45),
	ARTICULO VARCHAR(45) NULL,
	CODIGO VARCHAR(45)  NULL,
	DESCRIPCION VARCHAR(45) NOT NULL,
	MARCA VARCHAR(45)  NULL,
	LINEA VARCHAR(45)  NULL,
	CLAVE VARCHAR(45)  NULL,
	OBSERVACIONES VARCHAR(45)  NULL,
	FECHA VARCHAR(45)  NULL,
	FOTO VARCHAR(45) NULL,
	LINEAS VARCHAR(45) NULL,
	GRUPOS VARCHAR(45)  NULL,
	EXIST BOOLEAN  NULL DEFAULT 0,
	CANTIDAD INT(10) NULL,
	PRECIO FLOAT NOT NULL,
	PRECIO_LISTA FLOAT  NULL,
	ORDEN_ESPECIAL FLOAT NULL,
	PRECIO_ANTERIOR FLOAT  NULL,
	PRECIO_NUEVO FLOAT  NULL,
	PRECIO_NETO FLOAT NULL,
	INCREMENTO FLOAT  NULL,
	UXCTN FLOAT  NULL,
	PRECIO_L4 FLOAT  NULL,
	EQUIVALENCIA FLOAT  NULL,
	CANTIDAD_POR_CARTON INT(10)  NULL,
	REFERENCIA VARCHAR(45) NULL,
	STATUS VARCHAR(45) NULL,
	MULTIPLO VARCHAR(45) NULL,
		FOREIGN KEY (idPROVEEDOR) REFERENCES PROVEEDOR (idPROVEEDOR),
		FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (CATEGORIA));
-- -----------------------------------------------------
-- Table ORDEN
-- -----------------------------------------------------
DROP TABLE IF EXISTS ORDEN ;

CREATE TABLE IF NOT EXISTS ORDEN (
	idORDEN INT AUTO_INCREMENT PRIMARY KEY,
	idPRODUCTOS INT,
	ARTICULO VARCHAR(45)  NULL,
	DESCRIPCION VARCHAR(45) NOT NULL,
	PRECIO FLOAT NOT NULL,
		FOREIGN KEY (idPRODUCTOS) REFERENCES PRODUCTOS (idPRODUCTOS));
-- -----------------------------------------------------
-- Table CATEGORIA
-- -----------------------------------------------------
DROP TABLE IF EXISTS CATEGORIA ;

CREATE TABLE IF NOT EXISTS CATEGORIA (
	idCATEGORIA INT AUTO_INCREMENT NOT NULL,
	CATEGORIA VARCHAR(45)  NULL,
	DESCRIP_CATEGORIA VARCHAR(45)  NULL,
	CLASE VARCHAR(45)  NULL,
	GENERO VARCHAR(45)  NULL,
	ARMADOR VARCHAR(45) NULL,
	SERVICIO VARCHAR(45) NULL,
	NO_PARTE VARCHAR(45) NULL,
	ORIGEN VARCHAR(45)  NULL,
	UNIDAD VARCHAR(45)  NULL,
	PRIMARY KEY (idCATEGORIA, CATEGORIA));
